# Generated by Django 5.2.7 on 2026-03-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeaturedMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Знаем все нюансы продажи и покупки недвижимости",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Мы ведём YouTube-канал, на котором даём полезные советы и делаем обзоры недвижимости.",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube видео"),
                            ("image", "Изображение"),
                        ],
                        default="youtube",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(
                        blank=True,
                        verbose_name="Ссылка на YouTube (watch или youtu.be)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="featured_media/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        verbose_name="Ссылка на картинку (если не загружено)",
                    ),
                ),
                (
                    "link_label",
                    models.CharField(
                        blank=True,
                        default="Подписаться на канал",
                        max_length=100,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        default="https://www.youtube.com",
                        verbose_name="Ссылка кнопки",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на главной"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Медиа-блок (YouTube/картинка)",
                "verbose_name_plural": "Медиа-блоки на главной",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
