# Generated by Django 5.2.7 on 2026-03-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_default_featured_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        default="Отзыв клиента",
                        max_length=200,
                        verbose_name="Имя / подпись",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/",
                        verbose_name="Фото автора",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Показывать"),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("home_hero", "Главная — Hero"),
                            ("advantage_1", "Преимущества — карточка 1"),
                            ("advantage_2", "Преимущества — карточка 2"),
                            ("advantage_3", "Преимущества — карточка 3"),
                            ("advantage_4", "Преимущества — карточка 4"),
                            ("advantage_5", "Преимущества — карточка 5"),
                            ("advantage_6", "Преимущества — карточка 6"),
                            ("help_block", "Блок «Чем мы можем вам помочь»"),
                            ("cta_bg", "Призыв к действию — фон (все страницы)"),
                            ("about_image", "Страница «О нас»"),
                            ("purchase_hero", "Страница «Покупка» — Hero"),
                            ("sale_hero", "Страница «Продажа» — Hero"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sections/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Если не загружаете файл",
                        verbose_name="Или ссылка на изображение",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подпись в админке"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение секции",
                "verbose_name_plural": "Изображения секций",
            },
        ),
    ]
