# Generated by Django 5.2.12 on 2026-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_contact_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на фото"),
        ),
        migrations.AddField(
            model_name="review",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="reviews/videos/", verbose_name="Видео"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на видео"),
        ),
        migrations.AlterField(
            model_name="review",
            name="author_name",
            field=models.CharField(
                default="Отзыв клиента", max_length=200, verbose_name="ФИО"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="reviews/", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст отзыва"),
        ),
    ]
