# Generated by Django 5.2.12 on 2026-03-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_review_mock_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Должность"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="team/", verbose_name="Фото"
                    ),
                ),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="Если не загружаете файл с диска",
                        verbose_name="Ссылка на фото",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="О сотруднике")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Показывать на сайте"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["order", "id"],
            },
        ),
    ]
