# Generated by Django 5.2.12 on 2026-03-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_subscription_pro_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionimage",
            name="image_optimized",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Сжатая копия для быстрой загрузки (до 1920px). Создаётся при сохранении файла.",
                null=True,
                upload_to="sections/web/",
                verbose_name="Веб-версия (авто)",
            ),
        ),
    ]
