# Generated by Django 5.2.12 on 2026-03-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_sectionimage_image_optimized"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_badge",
                    models.CharField(
                        default="[ КОМАНДА ]",
                        help_text="Короткий верхний бейдж над заголовком.",
                        max_length=80,
                        verbose_name="Бейдж секции",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(
                        default="Наши сотрудники",
                        max_length=255,
                        verbose_name="Заголовок секции",
                    ),
                ),
                (
                    "section_description",
                    models.TextField(
                        default="Профессионалы, которые сопровождают сделки с недвижимостью: подбор объектов, переговоры, юридическая проверка и поддержка на каждом этапе.",
                        verbose_name="Описание секции",
                    ),
                ),
                (
                    "profile_label",
                    models.CharField(
                        default="Профиль",
                        max_length=80,
                        verbose_name="Заголовок на обороте карточки",
                    ),
                ),
                (
                    "empty_bio_fallback",
                    models.TextField(
                        default="Специалист агентства «Открытая Сделка». Поможет с подбором объекта, переговорами и сопровождением сделки.",
                        verbose_name="Текст по умолчанию (если bio пустой)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки страницы «Команда»",
                "verbose_name_plural": "Настройки страницы «Команда»",
            },
        ),
    ]
