# Generated by Django 5.2.12 on 2026-03-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "price",
                    models.CharField(
                        default="По запросу", max_length=100, verbose_name="Цена"
                    ),
                ),
                (
                    "rooms",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Комнат"),
                ),
                (
                    "area",
                    models.PositiveIntegerField(default=0, verbose_name="Площадь, м²"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="listings/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, verbose_name="Ссылка на фото (если не загружено)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты каталога",
                "ordering": ["-created_at"],
            },
        ),
    ]
