# Generated by Django 5.2.7 on 2026-03-14 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="listings/gallery/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="Ссылка на фото"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listingimage_set",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото в галлерее",
                "verbose_name_plural": "Фото в галлерее",
                "ordering": ["order"],
            },
        ),
    ]
