# Generated by Django 5.2.7 on 2026-03-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_listing_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "Продажа"), ("purchase", "Покупка")],
                default="sale",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
