# Generated by Django 5.2.12 on 2026-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_listing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_land_plot",
            field=models.BooleanField(default=False, verbose_name="Земельный участок"),
        ),
        migrations.AddField(
            model_name="listing",
            name="property_category",
            field=models.CharField(
                choices=[
                    ("residential", "Жилое"),
                    ("commercial", "Коммерческое помещение"),
                ],
                default="residential",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="realtor_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Имя риэлтора"
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="realtor_phone",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Телефон риэлтора"
            ),
        ),
    ]
