# Generated by Django 5.2.12 on 2026-03-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_public_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Генерируется автоматически при сохранении основного фото.",
                null=True,
                upload_to="listings/catalog/",
                verbose_name="Превью для каталога",
            ),
        ),
    ]
