# Демо-объекты каталога (только если БД объектов ещё пустая)

from django.db import migrations


def create_demo_listings(apps, schema_editor):
    Listing = apps.get_model('listings', 'Listing')
    if Listing.objects.exists():
        return

    demos = [
        {
            'title': 'Уютная двушка возле медцентра',
            'address': 'Бишкек, ул. Советская, 214',
            'listing_type': 'sale',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': '42 900 $',
            'price_usd': 42900,
            'rooms': 2,
            'area': 54,
            'description': 'Демонстрационный объект: светлые окна, кухня‑гостиная, счётчики отдельно.',
            'image_url': 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Квартира с видом на горы — 18 этаж',
            'address': 'Бишкек, ул. Абдрахманова, 157',
            'listing_type': 'sale',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': '138 500 $',
            'price_usd': 138500,
            'rooms': 4,
            'area': 128,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Компактная студия в новом доме',
            'address': 'Бишкек, мкр Джал, ул. Кольцевая, 12',
            'listing_type': 'sale',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': '28 700 $',
            'price_usd': 28700,
            'rooms': 1,
            'area': 32,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Трёхкомнатная с ремонтом под ключ',
            'address': 'Бишкек, Проспект Чуй, 95',
            'listing_type': 'sale',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': '195 000 $',
            'price_usd': 195000,
            'rooms': 3,
            'area': 96,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Офис 85 м² в бизнес-центре',
            'address': 'Бишкек, ул. Логвиненко, 22',
            'listing_type': 'sale',
            'property_category': 'commercial',
            'is_land_plot': False,
            'price': '320 000 $',
            'price_usd': 320000,
            'rooms': 3,
            'area': 85,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Участок ИЖС под застройку 8 соток',
            'address': 'с. Новопавловка, переулок Садовый',
            'listing_type': 'sale',
            'property_category': 'residential',
            'is_land_plot': True,
            'price': '67 800 $',
            'price_usd': 67800,
            'rooms': 1,
            'area': 800,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1599809275677-bbf2eae95921?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Роскошный дом с бассейном',
            'address': 'Пригород Лебединовка',
            'listing_type': 'sale',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': '890 000 $',
            'price_usd': 890000,
            'rooms': 6,
            'area': 380,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Покупка: ищем 2‑комн. до 115 000 $',
            'address': 'Приоритет: ЦУМ — Ошский рынок',
            'listing_type': 'purchase',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': 'До 115 000 $',
            'price_usd': 115000,
            'rooms': 2,
            'area': 62,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1570129477492-45c003edd374?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Просмотры в выходные: трёшка семье с детьми',
            'address': 'Бишкек, любой южный берег Аль-Арчин',
            'listing_type': 'purchase',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': 'До 85 500 $',
            'price_usd': 85500,
            'rooms': 3,
            'area': 78,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1600596542845-ea9c6c7d4c6c?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Пентхаус в премиальной новостройке',
            'address': 'Бишкек, пр. Жибек Жолу',
            'listing_type': 'sale',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': '512 000 $',
            'price_usd': 512000,
            'rooms': 4,
            'area': 152,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Уникальный лофт — цена при осмотре',
            'address': 'Бишкек, ул. Московская, центр',
            'listing_type': 'sale',
            'property_category': 'residential',
            'is_land_plot': False,
            'price': 'По запросу',
            'price_usd': None,
            'rooms': 2,
            'area': 88,
            'description': 'Без USD — объект не попадёт под числовой фильтр по цене.',
            'image_url': 'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=1200&q=80',
            'is_published': True,
        },
        {
            'title': 'Торговая площадь на первой линии',
            'address': 'Бишкек, пр. Чуй у перекрёстка с Тыныбаева',
            'listing_type': 'sale',
            'property_category': 'commercial',
            'is_land_plot': False,
            'price': '748 600 $',
            'price_usd': 748600,
            'rooms': 6,
            'area': 210,
            'description': '',
            'image_url': 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
            'is_published': True,
        },
    ]

    for row in demos:
        Listing.objects.create(**row)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_price_usd'),
    ]

    operations = [
        migrations.RunPython(create_demo_listings, migrations.RunPython.noop),
    ]
